dimensionality_reduction:
  PCA:
    - n_components: 10
    - n_components: 20
    - n_components: 30
    - n_components: 50
  ICA:
    - n_components: 10
    - n_components: 20
    - n_components: 30
  CCA:
    - n_components: 2
    - n_components: 5
    - n_components: 10
  LDA:
    - n_components: 2
    - n_components: 3
    - n_components: 5